export { default as Footer } from './Footer';
export { default as Header } from './Header';
export { default as AltaPrestamista } from './AltaPrestamista';
export { default as AltaCliente } from './AltaCliente';
export { default as DepositarGarantia } from './DepositarGarantia';
export { default as SolicitarPrestamo } from './SolicitarPrestamo';
export { default as AprobarPrestamo } from './AprobarPrestamo';
export { default as ReembolsarPrestamo } from './ReembolsarPrestamo';
export { default as LiquidarGarantia } from './LiquidarGarantia';
